source "https://rubygems.org"

# Specify your gem's dependencies in llm_mcp_meta_client.gemspec.
gemspec

gem "puma"

gem "sqlite3"

gem "propshaft"

# Authentication
gem "devise"

# OAuth providers
gem "omniauth"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"

# httparty
gem "httparty"

# JWT token
gem "jwt"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
